
url=http://103.25.172.47/VCMS_Optical/login/
#url=http://103.25.175.206/VCMS_Optical


#username=abhishek
#username=MUKESH
username=centralAdmin
#username=komal
password=MMJ@vcms
#password=Mukesh@123
#password=Komal@123

browser=chrome

